### ISSUE TITLE
OSBA Lab should state min K8s version

### ISSUE THREAD

**Issue by snpdev** [Azure/blackbelt-aks-hackfest#92] opened 2018-05-23 22:03 UTC
The lab instructions should state at the top, "Service Catalog currently works with Kubernetes version 1.9.0 and higher, so you will need a Kubernetes cluster that is version 1.9.0 or higher."

**Comment by razi-rais** [comment] 2018-07-05 15:52
Here is the documentation about mininum version requirements for OSBA (ver>=1.9.0) 
https://github.com/Azure/open-service-broker-azure/blob/fae43258eb8ff4c2e25f7b4da9879aae355eca73/docs/faq.md#osba-is-forbidden-not-yet-ready-to-handle-request.

**Proposed fix:** Either create a new AKS cluster in the OSBA lab with the correct version >=1.9.0 or change the lab1 so it provision the AKS cluster with version >=1.9.0 Currently, the AKS version used is 1.7.7. This may require some regression testing through to ensure all labs are working as expected with the version other than 1.7.7.

**Comment by mathieu-benoit** [comment] 2018-08-16 02:33
Thanks @snpdev and @razi-rais for the details. While implementing this PR #108 to set the K8S version to 1.10.6, it should fix this. Furthermore, I also indicated the note and the link you are referencing as documentation. Thanks!

**Comment by mathieu-benoit** [comment] 2018-09-20 13:30
FYI @chzbrgr71 or @jschluchter , this issue could be now closed since PR #108 has been merged into master.

**Closed** 2018-09-20 13:54 UTC
